# SPDX-License-Identifier: LGPL-2.1-or-later
# SPDX-FileCopyrightText: Canonical Ltd.
name: strace-static
version: "6.8"
summary: diagnostic, debugging and instructional userspace utility
description: |
  strace is a diagnostic, debugging and instructional userspace utility for Linux
build-base: core22
base: bare
confinement: strict
license: LGPL-2.1-or-later
assumes:
 - snapd2.64

apps:
  strace-static:
    command: bin/strace

parts:
  strace:
    plugin: autotools
    source: https://github.com/strace/strace/releases/download/v6.8/strace-6.8.tar.xz
    build-packages:
      - gawk
      - on s390x:
        - g++-multilib
        - gcc-multilib
      - on amd64:
        - g++-multilib
        - gcc-multilib
        - libiberty-dev
        - libunwind-dev
    override-pull: |
      craftctl default
      patch -p1 < ${CRAFT_PROJECT_DIR}/0001-tests-prepare-for-user-UID-GID-syntax.patch
      patch -p1 < ${CRAFT_PROJECT_DIR}/0002-strace-add-support-for-u-UID-GID-that-bypasses-looku.patch
    autotools-configure-parameters:
      - --prefix=/
      - --enable-mpers=check
      - LDFLAGS='-static -pthread'
    prime:
      - bin/strace
